# Webserver config
webserver:
  port: 7011

# View distance for every map display
view_distance: 100

# ping limit
ping_limit: 100

# Database config
database:
  type: sqlite
  file: "boiler.db"

# debug mode
debug: false
